// Generated by CoffeeScript 1.9.3
(function() {
  var LLNGHandler, http, https;

  http = require('http');

  https = require('https');

  require('llngconf');

  LLNGHandler = (function() {
    function LLNGHandler(arg) {
      var ref;
      this.confObj = (ref = args.conf) != null ? ref : new LemonldapConf();
    }

    return LLNGHandler;

  })();

  exports.llnghandler = new LLNGHandler;

}).call(this);
